# Generated by Django 4.1.5 on 2023-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserExtends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_registrate',
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='сотрудник'),
        ),
    ]
