# Generated by Django 4.1.5 on 2023-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserExtends', '0003_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='time_registrate',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
