# Generated by Django 4.1.5 on 2023-01-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserExtends', '0004_remove_user_last_login_user_time_registrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_registrate',
        ),
    ]
