# Generated by Django 4.1.5 on 2023-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserExtends', '0005_remove_user_time_registrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_registrate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
