# Generated by Django 4.1.5 on 2023-01-23 10:25

import UserExtend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=UserExtend.models.upload_to, verbose_name='Аватар')),
                ('time_registrate', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('approved', models.BooleanField(default=False, verbose_name='верифицирован')),
                ('banned', models.BooleanField(default=False, verbose_name='забанен')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
